spring:
  application:
    name: institution-management-service

  data:
    mongodb:
      url: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      database: institution-management-service